# Curate Metadata for C. thermocellum
- This is a copy of the template notebook for performing preliminary quality control on organism's expression data. In this case, C. thermocellum.
- Make any changes needed to output_qc/interim/sra_growth_metadata_ctherm_modified.xlsx, if needed

#### First run sra_metadata_retreiver.py to get all the data.

## Setup

In [1]:
import numpy as np
import pandas as pd

import re

from os import path

### Inputs

Enter path of QC1 passed metadata file and the metadata curated previously

In [ ]:
metadata_qc_file = path.join('.', 'output_qc', 'interim', 'metadata_qc_part1.tsv') # Enter filename for metadata QC file with only passing datasets from P1
metadata_qc_curated_file = path.join('.', 'output_qc', 'interim', 'sra_growth_metadata_ctherm_modified.xlsx') # Enter filename for metadata QC file with only passing datasets

metadata_qc_sra_curator_file = path.join('.', 'output_qc', 'interim', 'sra_growth_metadata_ctherm.csv') # Enter filename for metadata QC file with only passing datasets and created by sra_metadata_retreiver.py

In [3]:
df_metadata_qc = pd.read_csv(metadata_qc_file, sep='\t') #metadata that passed the QC1
df_metadata_qc.rename(columns={'Unnamed: 0': 'SRA_Accession'}, inplace=True)
df_metadata_qc.head()

,SRA_Accession,Run,ReleaseDate,LoadDate,spots,bases,spots_with_mates,avgLength,size_MB,AssemblyName,...,Submission,dbgap_study_accession,Consent,RunHash,ReadHash,R1,R2,passed_fastqc,passed_reads_mapped_to_CDS,passed_global_correlation
0,SRX1014220,SRR2002673,2015-11-02 10:20:11,2015-04-29 18:42:39,36341975,1817098750,0,50,726,NaN,...,SRA264897,NaN,public,A3EC42E71A32F705CCD0BF300141E74D,F321D5F6355C6DA0787479D43F9EB63B,NaN,NaN,True,True,True
1,SRX1014221,SRR2002674,2015-11-02 10:20:11,2015-04-29 18:42:02,23864175,1193208750,0,50,451,NaN,...,SRA264897,NaN,public,95EE0DF805E0029A110EB2E40D03CAB7,56D6E35162D9CAF9075718AD45D07BD7,NaN,NaN,True,True,True
2,SRX1014223,SRR2002676,2015-11-02 10:20:11,2015-04-29 18:42:24,30611161,1530558050,0,50,612,NaN,...,SRA264897,NaN,public,2683C28A4A7BABED88235DBAFAD3097D,E3E81F0B9E58372FABE9CCBD77EF6B8F,NaN,NaN,True,True,True
3,SRX1014225,SRR2002678,2015-11-02 10:20:11,2015-04-29 18:41:57,29139446,1456972300,0,50,590,NaN,...,SRA264897,NaN,public,C22A9E135A7A776706D4F38D49AA10B4,CA1933741920720D70F45184DF9B62A1,NaN,NaN,True,True,True
4,SRX1014226,SRR2002679,2015-11-02 10:20:11,2015-04-29 18:42:42,26904972,1345248600,0,50,540,NaN,...,SRA264897,NaN,public,C3902AAB5108342314079F48FB7EB6FA,AF2F16DF01DDB10CB8B54C209CFBBCB5,NaN,NaN,True,True,True

In [ ]:
df_metadata_curated_qc = pd.read_excel(metadata_qc_curated_file, sheet_name='curated_GOLD_for_circulation') #metadata that was curated previosuly from GOLD database
df_metadata_curated_qc.head()


# find columns that are not necessary
remove_cols = ['geo_loc_name', 'lat_lon', 'num_replicons', 'project_name', 'isol_growth_condt', 'env_broad_scale', 'ref_biomaterial', 'env_local_scale', 'collection_date', 'env_package', 'env_medium', 'investigation_type', 'cell_line', 'tissue', 'isolation_source', 'sample_type', 'sample time', 'Reactor', 'host', 'growth phase', 'isolate']
df_metadata_curated_qc_v1 = df_metadata_curated_qc.loc[:, [k for k in df_metadata_curated_qc.columns if k not in remove_cols]]

In [7]:
df_metadata_merged = pd.merge(df_metadata_qc, df_metadata_curated_qc_v1, on='SRA_Accession', how='inner')
print(df_metadata_merged.shape)

df_metadata_merged.head()

(112, 70)

,SRA_Accession,Run,ReleaseDate,LoadDate,spots,bases,spots_with_mates,avgLength,size_MB,AssemblyName,...,treatment,genotype,movement,batch,sulfur source,pH,temperature,growth_medium,method_desc,comments
0,SRX1014220,SRR2002673,2015-11-02 10:20:11,2015-04-29 18:42:39,36341975,1817098750,0,50,726,NaN,...,NaN,delta-hpt; delta-Clo1313_0089,NaN,1.0,NaN,7.0,58oC,MTC,NaN,highlighted in blue obtained from literature: ...
1,SRX1014221,SRR2002674,2015-11-02 10:20:11,2015-04-29 18:42:02,23864175,1193208750,0,50,451,NaN,...,NaN,delta-hpt; delta-Clo1313_0089,NaN,1.0,NaN,7.0,58oC,MTC,NaN,highlighted in blue obtained from literature: ...
2,SRX1014223,SRR2002676,2015-11-02 10:20:11,2015-04-29 18:42:24,30611161,1530558050,0,50,612,NaN,...,NaN,delta-hpt; delta-Clo1313_0089,NaN,1.0,NaN,7.0,58oC,MTC,NaN,highlighted in blue obtained from literature: ...
3,SRX1014225,SRR2002678,2015-11-02 10:20:11,2015-04-29 18:41:57,29139446,1456972300,0,50,590,NaN,...,NaN,delta-hpt; delta-Clo1313_0089,NaN,1.0,NaN,7.0,58oC,MTC,NaN,highlighted in blue obtained from literature: ...
4,SRX1014226,SRR2002679,2015-11-02 10:20:11,2015-04-29 18:42:42,26904972,1345248600,0,50,540,NaN,...,NaN,delta-hpt; delta-Clo1313_0089,NaN,1.0,NaN,7.0,58oC,MTC,NaN,highlighted in blue obtained from literature: ...

In [8]:
# manually remove these ids that need more curation
manual_add = ['SRX3200203',
                'SRX3200204',
                'SRX3200205',
                'SRX3200206',
                'SRX3200207',
                'SRX3200208',
                'SRX3200209',
                'SRX5209276',
                'SRX5209278']
df_metadata_merged = df_metadata_merged.loc[~df_metadata_merged['SRA_Accession'].isin(manual_add)]

In [9]:
no_data_sra_id = [k for k in df_metadata_qc['SRA_Accession'].to_list() if k not in df_metadata_merged['SRA_Accession'].to_list()]


df_metadata_qc_left = df_metadata_qc.loc[df_metadata_qc['SRA_Accession'].isin(no_data_sra_id)]
df_metadata_qc_left

,SRA_Accession,Run,ReleaseDate,LoadDate,spots,bases,spots_with_mates,avgLength,size_MB,AssemblyName,...,Submission,dbgap_study_accession,Consent,RunHash,ReadHash,R1,R2,passed_fastqc,passed_reads_mapped_to_CDS,passed_global_correlation
91,SRX298045,SRR891325,2020-11-19 12:54:38,2015-07-24 06:23:08,27708104,5541620800,27708104,200,3018,NaN,...,SRA089015,NaN,public,48A4759C578E297D68EFEC2F034869E7,6AF77BD60E6880C82171D564E6EEE4BA,NaN,NaN,True,True,True
92,SRX298054,SRR891336,2020-11-19 12:56:40,2015-07-24 06:17:13,29734690,5946938000,29734690,200,3279,NaN,...,SRA089015,NaN,public,9BE8D4A0166C4747294A8A362C378E5D,95CF23042FF4CD0C2D0A16A59E421F71,NaN,NaN,True,True,True
93,SRX298055,SRR891337,2020-11-19 12:56:40,2015-07-24 06:05:54,1689086,337817200,1689086,200,183,NaN,...,SRA089015,NaN,public,CD317A92B896B43EE11DE2A51253A30A,A34A0235D6B0AB097096E7AE6DF5FCB7,NaN,NaN,True,True,True
94,SRX298056,SRR891338,2020-11-19 12:58:39,2015-07-24 06:44:36,81762184,16352436800,81762184,200,9061,NaN,...,SRA089015,NaN,public,41E8B864B9909931F48FF34C53EC65F4,37EE295F3F447F6D04E2F3A56506CAA1,NaN,NaN,True,True,True
95,SRX298057,SRR891339,2020-11-19 13:00:37,2015-07-24 05:52:48,759999,151999800,759999,200,83,NaN,...,SRA089015,NaN,public,E3269AD6A6547A51958E549EB38346C7,0A022C682F5C7D5147466548DFF2BFC0,NaN,NaN,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,SRX7195458,SRR10506472,2019-11-22 17:43:27,2019-11-21 16:09:47,13624339,2752116478,13624339,202,1111,NaN,...,SRA1000146,NaN,public,8A62DEEEC0E3980EE4CBADCFDF571379,AFAC69D55620B6758B3870170D542414,NaN,NaN,True,True,True
250,SRX7195459,SRR10506471,2019-11-22 17:43:27,2019-11-21 16:11:29,16055505,3243212010,16055505,202,1322,NaN,...,SRA1000146,NaN,public,A2D4CE72A55A4D17BED1244FAC6B2705,7BAEE9E1B3FF26A3D8D8FAB7A174E4AF,NaN,NaN,True,True,True
251,SRX7195460,SRR10506470,2019-11-22 17:43:27,2019-11-21 16:13:59,14158030,2859922060,14158030,202,1140,NaN,...,SRA1000146,NaN,public,D45678A43CC5AD4FAC161D0FD9476ABF,B947CB52DC93436738EE421A6CBBADE3,NaN,NaN,True,True,True
252,SRX7195461,SRR10506469,2019-11-22 17:43:27,2019-11-21 16:19:03,14862052,3002134504,14862052,202,1195,NaN,...,SRA1000146,NaN,public,A12A43A55D2899C25F7407DB15D759D8,CF7B0CBA2BBDC9FDD7771D43BB8533D1,NaN,NaN,True,True,True
253,SRX7195462,SRR10506468,2019-11-22 17:43:27,2019-11-21 16:23:53,15961202,3224162804,15961202,202,1270,NaN,...,SRA1000146,NaN,public,7FB22BB9785609F04A019F06CEFE8575,153770CEA992D765D948D2ADDC1D6773,NaN,NaN,True,True,True

In [10]:
df_metadata_qc_left.loc[df_metadata_qc_left.SRA_Accession=='SRX5209276']

,SRA_Accession,Run,ReleaseDate,LoadDate,spots,bases,spots_with_mates,avgLength,size_MB,AssemblyName,...,Submission,dbgap_study_accession,Consent,RunHash,ReadHash,R1,R2,passed_fastqc,passed_reads_mapped_to_CDS,passed_global_correlation
156,SRX5209276,SRR8399980,2019-01-05 20:28:48,2019-01-05 20:26:28,14141185,2856519370,14141185,202,1119,NaN,...,SRA831135,NaN,public,E1EF3C84A3167BC917BBC39999F7037E,88AAFFF4250D57E5043F9693A9028D6D,NaN,NaN,True,True,True

In [11]:
df_metadata_merged_v1 = pd.concat([df_metadata_merged, df_metadata_qc_left], axis=0)
df_metadata_merged_v1.head()

,SRA_Accession,Run,ReleaseDate,LoadDate,spots,bases,spots_with_mates,avgLength,size_MB,AssemblyName,...,treatment,genotype,movement,batch,sulfur source,pH,temperature,growth_medium,method_desc,comments
0,SRX1014220,SRR2002673,2015-11-02 10:20:11,2015-04-29 18:42:39,36341975,1817098750,0,50,726,NaN,...,NaN,delta-hpt; delta-Clo1313_0089,NaN,1.0,NaN,7.0,58oC,MTC,NaN,highlighted in blue obtained from literature: ...
1,SRX1014221,SRR2002674,2015-11-02 10:20:11,2015-04-29 18:42:02,23864175,1193208750,0,50,451,NaN,...,NaN,delta-hpt; delta-Clo1313_0089,NaN,1.0,NaN,7.0,58oC,MTC,NaN,highlighted in blue obtained from literature: ...
2,SRX1014223,SRR2002676,2015-11-02 10:20:11,2015-04-29 18:42:24,30611161,1530558050,0,50,612,NaN,...,NaN,delta-hpt; delta-Clo1313_0089,NaN,1.0,NaN,7.0,58oC,MTC,NaN,highlighted in blue obtained from literature: ...
3,SRX1014225,SRR2002678,2015-11-02 10:20:11,2015-04-29 18:41:57,29139446,1456972300,0,50,590,NaN,...,NaN,delta-hpt; delta-Clo1313_0089,NaN,1.0,NaN,7.0,58oC,MTC,NaN,highlighted in blue obtained from literature: ...
4,SRX1014226,SRR2002679,2015-11-02 10:20:11,2015-04-29 18:42:42,26904972,1345248600,0,50,540,NaN,...,NaN,delta-hpt; delta-Clo1313_0089,NaN,1.0,NaN,7.0,58oC,MTC,NaN,highlighted in blue obtained from literature: ...

In [12]:
# load the output data from sra_metadata_retreiver.py
df_metadata_sra_curator = pd.read_csv(metadata_qc_sra_curator_file)

In [13]:
df_eh_curator = pd.read_excel('./output_qc/interim/sra_growth_metadata_ctherm_modified.xlsx', sheet_name='mapping_data_for_EH')

In [14]:
df_metadata_merged_v1['proj_special'] = ''

# df = pd.DataFrame(columns=['proj', 'date_exp', 'strain'])
                  
for acc in df_metadata_qc_left['SRA_Accession'].to_list():
    if acc in df_metadata_sra_curator['accession'].to_list():
            df_row = df_metadata_sra_curator.loc[df_metadata_sra_curator.accession==acc]
            sample_name = df_row['bs__title'].values[0]

            if re.match(r'^Ruminiclostridium thermocellum \w+ transcriptomics - ', sample_name) or re.match(r'^Ruminiclostridium thermocellum DSM1313 \w+ transcriptomics - ', sample_name):
                # date_exp = re.findall(r'_\d+_\d+_\d+_', sample_name)
                # date_exp = date_exp[0].strip('_')
                # date_exp = date_exp.replace('_', '-')
                
                # proj_name = re.findall(r'LL\d+ transcriptomics', sample_name)
                # proj_name = re.sub('transcriptomics$', '', proj_name[0])

            
                # proj_name = re.findall(r'_C(I|II|III|IV)_', sample_name)
                # proj_name = re.sub('_', '', proj_name[0])
                # if proj_name=='I' or proj_name=='II':
                #      proj_name_mod = 'I-II'
                # elif proj_name=='III' or proj_name=='IV':
                #      proj_name_mod = 'III-IV'
                     

                # # # proj_name = re.findall(r'LL\d+ transcriptomics', sample_name)
                # # # proj_name = re.sub('transcriptomics$', '', proj_name[0])

                # # # if proj_name not in dict_proj_strains.keys():
                # # #     dict_proj_strains[proj_name] = list()
                
                sample_name = re.sub(r'^Ruminiclostridium thermocellum \w+ transcriptomics - ', '', sample_name)
                sample_name = re.sub(r'-v\d$', '', sample_name)
                strain_name = re.findall(r'LL\d+', sample_name)
                strain_name = strain_name[0]

                # df.loc[acc] = proj_name, date_exp, strain_name
                
                df_metadata_merged_v1.loc[df_metadata_merged_v1.SRA_Accession==acc, 'strain'] = strain_name

                # df_metadata_merged_v1.loc[df_metadata_merged_v1.SRA_Accession==acc, 'proj_special'] = 'eh_chemostat_C' + proj_name_mod
                df_metadata_merged_v1.loc[df_metadata_merged_v1.SRA_Accession==acc, 'proj_special'] = 'eh_chemostat'

                
                if sample_name.endswith('_Nlimit'):
                    df_metadata_merged_v1.loc[df_metadata_merged_v1.SRA_Accession==acc, 'treatment'] = 'N-limited'
                else:
                    df_metadata_merged_v1.loc[df_metadata_merged_v1.SRA_Accession==acc, 'treatment'] = df_row['bs__treatment'].values[0]

                df_metadata_merged_v1.loc[df_metadata_merged_v1.SRA_Accession==acc, 'batch'] = 0
                
            else:
                df_metadata_merged_v1.loc[df_metadata_merged_v1.SRA_Accession==acc, 'strain'] = df_row['bs__strain'].values[0]
                df_metadata_merged_v1.loc[df_metadata_merged_v1.SRA_Accession==acc, 'treatment'] = df_row['bs__treatment'].values[0]
            
            df_metadata_merged_v1.loc[df_metadata_merged_v1.SRA_Accession==acc, 'csource'] = df_row['bs__carbon_source'].values[0]
            df_metadata_merged_v1.loc[df_metadata_merged_v1.SRA_Accession==acc, 'time point sampled'] = df_row['bs__time_point_sampled'].values[0]
            df_metadata_merged_v1.loc[df_metadata_merged_v1.SRA_Accession==acc, 'sulfur source'] = df_row['bs__sulfur_source'].values[0]
            df_metadata_merged_v1.loc[df_metadata_merged_v1.SRA_Accession==acc, 'pH'] = df_row['bs__ph_of_chemostat'].values[0]

In [17]:
# add publication data from SRA curated file
keep_cols = ['accession', 'pub__pmid', 'pub__title', 'pub__first_author', 'pub__authors', 'pub__journal', 'pub__year', 'pub__doi']

df_metadata_sra_curator_v1 = df_metadata_sra_curator[keep_cols]


df_metadata_sra_curator_v1.rename(columns={'accession': 'SRA_Accession'}, inplace=True)
# now concat
df_metadata_merged_v2 = pd.merge(df_metadata_merged_v1, df_metadata_sra_curator_v1, on='SRA_Accession', how='inner')

/var/folders/8c/yy8ts7rn59j58vl5_l6jgcmd1lvs3b/T/ipykernel_93157/2155506188.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_metadata_sra_curator_v1.rename(columns={'accession': 'SRA_Accession'}, inplace=True)

In [18]:
df_metadata_merged_v2.to_csv('./output_qc/interim/sra_growth_metadata_ctherm_curated_p1.tsv', sep='\t') #first curation with curated file + SRA curation

### FIN